<?php

/*
 * File: Strings_Castellano.php
 *
 * Traductions for Spanish
 * 
 * Author: ivanddios <ivanddf1994@gmail.com>
 */

$strings = array(
    "Welcome"=> "Bienvenido",
    "Add"=> "Añadir",
    "Edit" => "Editar",
    "Show" => "Ver",
    "Delete" => "Eliminar",
    "Search" => "Buscar",
    "EditProfile" => "EditProfile",
    "Building" => "Edificio: ",
    "Buildings" => "Edificios",
    "Show Buildings" => "Ver Edificios",
    "Admin" => "Administración",
    "My Profile" => "Mi Perfil",
    "Logout" => "Salir",
    "Login" => "Login",
    "Function" => "Funcionalidad",
    "Functionalities" => "Funcionalidades",
    "Permissions" => "Roles",
    "Spanish" => "Castellano",
    "Galician" => "Galego",
    "English" => "English",
    "Users" => "Usuarios",
    "Do you want to change something?" => "¿Quieres modificar algún dato?",
    "Save" => "  Guardar",
    "Back" => "Volver",
    "Extend" => "Ampliar",
    "Adjust" => "Ajustar",
    "Close" => "Cerrar",
    "Help" => "Ayuda",
    "Demonstration" => "Demostración",
    "selectAll" => "Selecciona todas las acciones",
    "Tests"=>"Tests",
    "SearchTest" =>"Filtra por Valid o Error",
    "Error in the query on the database" => "Error en la consulta sobre la base de datos",

    //BUILDING
    "sm_idBuilding" => "Identificador",
    "sm_nameBuilding" => "Edificio ",
    "sm_addressBuilding" => "Dirección",
    "sm_phoneBuilding" => "Teléfono",
    "idBuilding" => "Identificador del edificio",
    "nameBuilding" => "Edificio",
    "addressBuilding" => "Dirección",
    "phoneBuilding" => "Teléfono",
    "Floors" => "Plantas",
    "Show Floor" => "Ver planta",
    "Edit Building" => "Editar Edificio",
    "Delete Building" => "Eliminar Edificio",
    "Add Building" => "Añadir Edificio",
    "Show Building" => "Ver Edificio",
    "seeFloors" => "Para ver las plantas del edificio pulsa ",
    "Attention" => "Atención",
    "Are you sure you want to delete the building \"%s\" ?" => "¿Está seguro de querer eliminar el edificio \"%s\" ?",
    "The information that this building has will be lost" => "La información que tiene este edificio se perderá",
    "Cancel" => "Cancelar",
    "Ok" => "Ok",
    "Datas of the new building" => "Datos del nuevo edificio",
    "What is the identifier of this building?" => "¿Cuál es el identificador de este edificio?",
    "What building is it?" => "¿Qué edificio es?",
    "What is its postal address?" => "¿Cuál es su dirección?",
    "What is its phone?" => "¿Cuál es su teléfono?",
    "Not in session. Add buildings requires login." => "Para añadir edificios debes estar loggueado",
    "Not in session. Edit buildings requires login." => "Para editar edificios debes estar loggueado",
    "Not in session. Delete buildings requires login." => "Para eliminar edificios debes estar loggueado",
    "You don't have the necessary permits" => "No tienes los permisos necesarios",
    "Building \"%s\" successfully added." => "El edificio \"%s\" se ha añadido con éxito",
    "Building \"%s\" successfully deleted." => "El edificio \"%s\" se ha eliminado con éxito",
    "Building \"%s\" successfully updated." => "El edificio \"%s\" se ha modificado con éxito",

    //FLOOR
    "Floor" => "Planta: ",
    "Information about the building's floors" =>"Información sobre las plantas del edificio",
    "idBuildingidFloor" => "Identificador",
    "sm_idFloor" => "Identificador",
    "sm_nameFloor" => "Piso",
    "sm_planFloor" => "Plano",
    "idFloor" => "Identificador de la planta",
    "nameFloor" => "Planta",
    "builtSurfaceFloor" => "Superficie construida",
    "surfaceUsefulFloor" => "Superficie útil",
    "Click to see the plan" => "Click para ver el plano",
    "sm_builtSurfaceFloor" => "Sup. Construida",
    "sm_surfaceUsefulFloor" => "Sup. Útil",
    "Show Spaces" => "Ver Espacios",
    "Add Floor" => "Añadir Planta",
    "Edit Floor" => "Editar Planta",
    "Delete Floor"=>"Eliminar Planta",
    "Show Floors" => "Ver Plantas",
    "seeSpaces" => "Para ver los espacios de esta planta pulsa ",
    "here" => "aquí",
    "Are you sure you want to delete the floor \"%s\"?" => "¿Está seguro de querer eliminar la planta \"%s\"?",
    "The information that this floor has will be lost" => "La información que tiene esta planta se perderá",
    "Data of the new building's floor" => "Datos del nuevo piso del edificio",
    "What is the identifier of this floor?" => "¿Cuál es el identificador de la planta? ",
    "What floor is it?" => "¿Qué planta es? ",
    "Is there a plan for this floor?" => "¿Hay plano de esta planta?",
    "What is the constructed surface?" => "¿Cuál es la superficie construída?",
    "What is the useful surface?" => "¿Cuál es la superficie útil?",
    "Not in session. Add floors requires login." => "Para añadir plantas debes estar loggueado",
    "Not in session. Edit floors requires login." => "Para editar plantas debes estar loggueado",
    "Not in session. Delete floors requires login." => "Para eliminar plantas debes estar loggueado",
    "Building id is mandatory" => "El identificador del edificio es obligatorio",
    "Floor \"%s\" successfully updated." => "La planta \"%s\" se ha modificado con éxito",
    "Floor \"%s\" successfully added." => "La planta \"%s\" se ha añadido con éxito",
    "Floor \"%s\" successfully deleted." => "La planta \"%s\" se ha eliminado con éxito",
    "Show Plan" => "Ver Plano",

    //SPACE
    "Information about the building's spaces" => "Información sobre los espacios del edificio",
    "Spaces" => "Espacios",
    "sm_idSpace" => "Identificador",
    "What is its category?" => "¿Qué categoría es?",
    "Infraestructura" => "Infraestructura",
    "PAS" => "PAS",
    "Servicios" => "Servicios",
    "Docencia" => "Docencia",
    'sm_categorySpace' => "Categoría",
    "SpaceOf" => "Espacio de ",
    "sm_nameSpace" => "Espacio",
    "sm_builtSurface" => "Sup. Espacio",
    "sm_numberInventorySpace" => "Núm. Inventario",
    "Show Space" => "Ver Espacio",
    "Add Space" => "Añadir Espacio",
    "Edit Space" => "Editar Espacio",
    "Delete Space" => "Eliminar Espacio",
    "Show Space" => "Ver Espacio",
    "SelectSpacePlan" => "SelectSpacePlan",
    "ShowSpacePlan" => "ShowSpacePlan",
    "EditSpacePlan" => "EditSpacePlan",
    "Are you sure you want to delete the space \"%s\" ?" => "¿Está seguro de querer eliminar el espacio \"%s\" ?",
    "The information that this space has will be lost" => "La información que tiene este espacio se perderá",
    "Clear" => "Eliminar",
    "Space successfully updated in plan" => "Espacio correctamente actualizado en el plano",
    "Select the space in the plan" => "Seleccione la ubicación del espacio",
    "ViewSpace" => "Ver Espacio",
    "SelectSpace" => "Seleccionar Espacio",
    "EditSpace" => "Editar Espacio",
    "Data of the new space" => "Datos del nuevo espacio",
    "What is the identifier of this space?" => "¿Cuál es el identificador del nuevo espacio?",
    "What space is it?" => "¿Qué espacio es?",
    "What is the number inventory?" => "¿Cuál es su número de inventario?",
    "What is the surface of space?" => "¿Cuál es la superficie del espacio?",
    "Space \"%s\" successfully added." => "El espacio \"%s\" se ha añadido con éxito",
    "Space \"%s\" successfully updated." => "El espacio \"%s\" se ha actualizado con éxito",
    "Space \"%s\" successfully deleted." => "El espacio \"%s\" se ha eliminado con éxito",
    "Building, floor and space id are mandatory" => "El id del edificio, la planta y el espacio son obligatorios",
    "Building and floor id are mandatory" => "El id del edificio y la planta son obligatorios",
    "Not in session. Add space requires login." => "Para añadir un espacio debes estar logueado",
    "Not in session. Edit space requires login." => "Para modificar un espacio debes estar logueado",
    "Not in session. Delete space requires login." => "Para eliminar un espacio debes estar logueado",
    "Click to edit the space in the plan" => "Click para modificar el espacio en el plano",
    "Click to see the space in the plan" => "Click para ver el espacio en el plano",

    //USER
    "User" => "Usuario",
    "photo" => "Foto",
    "passwd" => "Contraseña",
    "name" => "Nombre",
    "surname"=> "Apellidos",
    "dni" => "DNI",
    "birthdate" => "Fecha",
    "email" => "Email",
    "phone" => "Teléfono",
    "ProfilePhoto" => "Foto de perfil",
    "Show Users" => "Ver Usuarios",
    "User \"%s\" successfully added." => "El usuario \"%s\" se ha añadido con éxito",
    "User \"%s\" successfully updated." => "El usuario \"%s\" se ha actualizado con éxito",
    "User \"%s\" successfully deleted." => "El usuario \"%s\" se ha eliminado con éxito",
    "Not in session. Add users requires login." => "Para añadir usuarios debes estar logueado",
    "Not in session. Edit user requires login." => "Para editar un usuario debes estar logueado",
    "Not in session. Add users requires login." => "Para eliminar usuarios debes estar logueado",
    "You can't modify the data of another user" => "No puedes modificar los datos de otros usuarios",
    "Are you sure you want to delete the user \"%s\" ?" => "¿Está seguro de querer eliminar el usuario \"%s\" ?",
    "The information that this user has will be lost" => "La información que tiene este usuario se perderá",
    "Add User" => "Añadir Usuario",
    "Show User" => "Ver Usuario",
    "Edit User" => "Editar Usuario",
    "Delete User" => "Eliminar Usuario",
    "Search User" => "Buscar Usuario",
    "New user" => "Nuevo Usuario",
    "UserInfo" => "Información del usuario",
    "What is the email of this user?" => "¿Cuál es el email?",
    "What is the password of this user?" => "¿Cuál es la contraseña del usuario?",
    "Repeat password" => "Vuelva a escribir la contraseña",
    "Repeat new password" => "Vuelva a escribir la contraseña",
    "What is the name of the user?" => "¿Cuál es el nombre del usuario?",
    "What are the user's surnames?" => "¿Cuáles son los apellidos del usuario?",
    'What is its ID?' => "¿Cuál es el DNI del usuario? ",
    "What is his birthdate?" => "¿Cuál es la fecha de nacimiento del usuario?",
    "What is his email?" => "¿Cuál es el email del usuario? ",
    "What is his phone?" => "¿Cuál es el teléfono del usuario?",
    "What is his group?" => "¿Cuál es su rol?",
    "Do you want to change the password?" => "¿Quieres cambiar la contraseña? ",
    "PasswordCharacters"=> "Mínimo 8 caracteres",
    "PasswordLowercase"=> "Una minúscula",
    "PasswordUppercase"=> "Una mayúscula",
    "PasswordNumber"=> "Un número",
    "Choose" => "Selecciona uno",
    "Search user/s" => "Busca usuario/s",
    "No User" => "No existe ningún usuario con esos datos",

    //FUNCTIONALITIES
    "Function: " => "Funcionalidad: ",
    "idFunction" => "Identificador de la funcionalidad",
    "nameFunction" => "Nombre de la funcionalidad",
    "descripFunction" => "Descripción de la funcionalidad",
    "Functionalities" => "Funcionalidades",
    "sm_nameFunction" => "Funcionalidad",
    "sm_descripFunction" => "Descripción",
    "Add Functionality" => "Nueva Funcionalidad",
    "Show Functionality" => "Ver Funcionalidad",
    "Edit Functionality" => "Editar Funcionalidad",
    "Delete Functionality" => "Eliminar Funcionalidad",
    "Datas of the new functionality" => "Datos de la nueva funcionalidad",
    "What functionality is it?" => "¿Qué funcionalidad es?",
    "What is the functionality about?" => "¿De qué trata la funcionalidad?",
    "Check the actions:" => "Seleccione las acciones:",
    "Actions associated with functionality:" => "Acciones asociadas con la funcionalidad:",
    "Are you sure you want to delete the functionality \"%s\" ?" => "¿Está seguro de querer eliminar la funcionalidad \"%s\" ?",
    "The information that this functionality has will be lost" => "La información de esta funcionalidad se perderá",
    "Function id is mandatory" => "El id de la funcionalidad es obligartorio",
    "Not in session. Add functionalities requires login." => "Para añadir funcionalidades debes estar loggueado",
    "Not in session. Edit functionalities requires login." => "Para editar funcionalidades debes estar logueado",
    "Not in session. Delete functionalities requires login." => "Para eliminar funcionalidades debes estar logueado",
    "Not in session. Show function requires login." => "Para ver una funcionalidad debes estar logueado",
    "Functionality \"%s\" successfully added." => "La funcionalidad \"%s\" se ha añadido con éxito",
    "Function \"%s\" successfully updated." => "La funcionalidad \"%s\" se ha modificado con éxito",
    "Function \"%s\" successfully deleted." => "La funcionalidad \"%s\" se ha eliminado con éxito",

    //GROUP
    "Groups" => "Roles",
    "sm_nameGroup" => "Rol",
    "sm_descripGroup" => "Descripción",
    "Group id is mandatory" => "El identificador del rol es obligatorio",
    "Add Group" => "Añadir Rol",
    "Delete Group" => "Eliminar Rol",
    "Edit Group" => "Editar Rol",
    "Show Group" => "Ver Rol",
    "ShowUsersForGroup" => "ShowUsersForGroup",
    "Are you sure you want to delete the group \"%s\" ?" => "¿Está seguro de querer eliminar el rol \"%s\" ?",
    "The information that this group has will be lost" => "La información de este rol se perderá",
    "Not in session. Add group requires login." => "Para añadir roles debes estar logueado",
    "Not in session. Delete groups requires login." => "Para eliminar roles debes estar logueado",
    "Not in session. Edit groups requires login." => "Para modificar roles debes estar logueado",
    "Group \"%s\" successfully added." => "El rol \"%s\" se ha añadido con éxito",
    "Group \"%s\" successfully updated." => "El rol \"%s\" se ha modificado con éxito",
    "Group \"%s\" successfully deleted." => "El rol \"%s\" se ha eliminado con éxito",
    "Datas of the new group" => "Datos del nuevo rol",
    "What group is it?" => "¿Nombre del Rol?",
    "What is the group about?" => "Describe el rol brevemente",
    "SelectActionsFunction" => "Selecciona las acciones de cada funcionalidad",
    "ModifyActionsFunction" => "Modifica las acciones de cada funcionalidad",

    //ACTION
    "Action :" => "Acción: ",
    "idAction" => "Identificador de la acción",
    "nameAction" => "Nombre de la acción",
    "descripAction" => "Descripción de la acción",
    "Not in session. Add actions requires login." => "Para añadir acciones debes estar logueado",
    "Not in session. Delete actions requires login." => "Para eliminar acciones debes estar logueado",
    "Not in session. Edit actions requires login." => "Para modificar acciones debes estar logueado",
    "Not in session. Show action requires login." => "Para ver una acción debe estar logueado",
    "Actions" => "Acciones",
    "sm_nameAction" => "Acción",
    "sm_descripAction" => "Descripción",
    "Add Action" => "Añadir Acción",
    "Delete Action" => "Eliminar Acción",
    "Edit Action" => "Editar Acción",
    "Show Action" => "Ver Acción",
    "Are you sure you want to delete the action \"%s\" ?" => "¿Está seguro de querer eliminar la acción \"%s\" ?",
    "The information that this action has will be lost" => "La información de esta acción se perderá",
    "Action id is mandatory" => "El identificador de la acción es obligatorio",
    "Action \"%s\" successfully added." => "La acción \"%s\" se ha añadido con éxito",
    "Action \"%s\" successfully updated." => "La acción \"%s\" se ha modificado con éxito",
    "Action \"%s\" successfully deleted." => "La acción \"%s\" se ha eliminado con éxito",
    "Datas of the new action" => "Datos de la nueva acción",
    "What action is it?" => "¿Nombre de la acción?",
    "What is the action about?" => "Describe la acción brevemente",


    //VALIDATES ERRORS
    //BUILDING
    "Building identifier is mandatory" => "El identificador del edificio es obligatorio",
    "Building identifier can't be less than 5 characters" => "El identificador del edificio no puede tener menos de 5 caracteres",
    "Building identifier can't be larger than 5 characters" =>"El identificador del edificio no puede tener más de 5 caracteres",
    "Building identifier format is invalid" => "El formato del identificador es incorrecto",
    "Building name is mandatory" => "El nombre del edificio es obligatorio",
    "Building name can't be larger than 255 characters" => "El nombre del edificio no puede tener más de 255 caracteres",
    "Building name format is invalid" => "El formato del nombre del edificio es incorrecto",
    "Building address is mandatory" => "La dirección del edificio es obligatoria",
    "Building address can't be larger than 255 characters" => "La dirección del edificio no puede tener más de 255 caracteres",
    "Building address format is invalid" => "El formato de la dirección del edificio es incorrecta",
    "Building phone is incorrect" => "El teléfono del edificio es incorrecto",
    "Building phone format is invalid" => "El teléfono es incorrecto",
    "There is already a building with that identifier" => "Ya existe un edificio con ese identificador",
    "There isn't a building with that identifier" => "No existe ningún edificio con ese identificador",

    //FLOOR
    "Floor identifier is mandatory" => "El identificador de la planta es obligatorio",
    "Floor identifier can't be less than 2 characters" => "El identificador de la planta no puede tener menos de 2 caracteres",
    "Floor identifier can't be larger than 2 characters" => "El identificador de la planta no puede tener más de 2 caracteres",
    "Floor identifier format is invalid" => "El formato del identificador es incorrecto",
    "Floor name is mandatory" => "El nombre de la planta es obligatorio",
    "Floor name can't be larger than 255 characters" => "El nombre de la planta no puede tener más de 255 caracteres",
    "Floor name format is invalid" => "El nombre es inválido",
    "Floor building surface can't be long than 99999999.99" => "La superficie de la planta no puede ser más grande de 99999999.99",
    "Floor useful surface can't be long than 99999999.99" => "La superficie útil de la planta no puede ser más grande de 99999999.99",
    "The usable surface can't be greater than the building surface" => "La superficie útil de la planta no puede ser mayor que la superficie construída",
    "Floor plan extension is invalid" => "La extensión del plano es incorrecta. Solo se aceptan imágenes.",
    "There is already a floor with that id in this building" => "Ya existe una planta con ese identificador en este edificio",
    "There isn't a floor with that identifier in the building" => "No existe ninguna planta con ese identificador en este edificio",

    //SPACE
    "Space identifier is mandatory" => "El identificador del espacio es obligatorio",
    "Space identifier can't be less than 5 characters" => "El id del espacio no puede tener menos de 5 caracteres",
    "Space identifier can't be larger than 5 characters" => "El id del espacio no puede tener más de 5 caracteres",
    "Space identifier is invalid" => "El formato del identificador del espacio es incorrecto",
    "Space category is invalid" => "La categoría del espacio es incorrecta",
    "Space name is mandatory" => "El nombre del espacio es obligatorio",
    "Space name can't be larger than 225 characters" => "El nombre del espacio o puede tener más de 225 caracteres",
    "Space name format is invalid" => "El formato del nombre del espacio es incorrecto",
    "Space surface can't be larger than 99999999.99" => "La superficie del espacio no puede ser más grande de 99999999.99",
    "Number inventory can't be larger than 6 characters" => "El número de inventario no puede tener más de 6 caracteres",
    "Coords can't be larger than 65535 characters" => "Las coordenadas del espacio son demasiado grandes",
    "Coords format is invalid" => "El formato de las coordenadas del espacio es incorrecto",
    "There is already a space with that identifier in this floor" => "Ya existe un espacio con ese identificador en esta planta",
    "There isn't a space with that identifier in the floor" => "No existe ningún espacio con ese identificador en esta planta",

    //USER
    "Email is mandatory" => "El email es obligatorio",
    "Email can't be larger than 50 characters" => "El email no puede tener más de 50 caracteres",
    "Email format is invalid" => "El formato del email es incorrecto",
    "There isn't a user with that email" => "No existe ningún usuario con ese email",
    "There is already a user with that email in this aplication" => "Ya existe un usuario con ese email en esta aplicación",
    "There is already a user with that email" => "Ya existe un usuario con ese email",
    "Password is mandatory" => "La contraseña es obligatoria",
    "Password can't be less than 8 characters" => "La contraseña no puede tener menos de 8 caracteres",
    "Password can't be larger than 16 characters" => "La contraseña no puede tener más de 16 caracteres",
    "Password format is invalid" => "La formato de la contraseña es incorrecto",
    "Password is incorrect" => "La contraseña es incorrecta",
    "User name is mandatory" => "El nombre del usuario es obligatorio",
    "User name can't be larger than 40 characters" => "El nombre del usuario no puede tener más de 40 caracteres",
    "User name format is invalid" => "El formato del nombre del usuario es incorrecto",
    "User surnames are mandatory" => "Los apellidos son obligatorios",
    "User surnames can't be larger than 100 characters" => "Los apellidos no pueden tener más de 100 caracteres",
    "User surnames format is invalid" => "Los formato de los apellidos es incorrecto",
    "NID can't be different from 9 characters" => "El tamaño del DNI es incorrecto",
    "User NID format is invalid" => "El formato del DNI es incorrecto",
    "User NID letter is incorrect" => "La letra del DNI es incorrecta",
    "Birthdate is mandatory" => "La fecha de nacimiento es obligatoria",
    "Birthdate can't be larger than 10 characters" => "La fecha de nacimiento no puede tener más de 10 caracteres",
    "Birthdate format is invalid" => "El formato de la fecha de nacimiento es incorrecto",
    "User phone size is incorrect" => "El tamaño del teléfono es incorrecto",
    "User phone format is invalid" => "El formato del teléfono es incorrecto",
    "The role format is invalid" => "El formato del rol es incorrecto",
    "The role doesn't exist" => "El rol no existe en el sistema",
    "There is another user with that DNI in the DB" => "Ya hay otro usuario con ese DNI",
    "The image extension is incorrect" => "La extensión de la imagen es inválida",
    "Your user had been deleted." => "Tu usuario ha sido eliminado",
    "Not exists this account" => "No existe la cuenta de usuario",
    "There is a user with that email" => "Ya existe un usuario con ese email",

    //ACTION
    "Action identifier is mandatory" => "El identificador de la acción es obligatorio",
    "Action identifier format is invalid" => "El formato del identificador es incorrecto",
    "Action name and description are mandatory" => "El nombre y la descripción de la acción es obligatorio",
    "Action name is mandatory" => "El nombre de la acción es obligatorio",
    "Action name can't be larger than 50 characters" => "El nombre de la acción no puede tener más de 50 caracteres",
    "Action name format is invalid" => "El formato del nombre de la acción es incorrecto",
    "Action description is mandatory" => "La descripción de la acción es obligatoria",
    "Action description can't be larger than 255 characters" => "La descripción no puede tener más de 255 caracteres",
    "Action description format is invalid" => "El formato de la descripción de la acción es incorrecto",
    "Action doesn't exist" => "La acción no existe",

    //FUNCTIONALITY
    "Function identifier is mandatory" => "El identificador de la funcionalidad es obligatorio",
    "Function identifier format is invalid" => "El formato del identificador de la funcionalidad es incorrecto",
    "Function name and description are mandatory" => "El nombre y la descripción de la funcionalidad es obligatorio",
    "Function name is mandatory" => "El nombre de la funcionalidad es obligatorio",
    "Function name can't be larger than 50 characters" => "El nombre de la funcionalidad no puede tener más de 50 caracteres",
    "Function name format is invalid" => "El formato del nombre de la funcionalidad es incorrecto",
    "Function description is mandatory" => "La descripción de la funcionalidad es obligatorio",
    "Function description can't be larger than 255 characters" => "La descripción de la funcionalidad no puede tener más de 255 caracteres",
    "Function description format is invalid" => "El formato de la descripción de la funcionalidad es incorrecto",
    "Access to some functionality is mandatory" => "La funcionalidad debe estar asociada a por lo menos una acción",
    "Some action for functionality doesn't exist" => "Alguna de las acciones de la funcionalidad no existe",
    "Function doesn't exist" => "La funcionalidad no existe",

    //GROUP
    "Group identifier is mandatory" => "El identificador del role es obligatorio",
    "Group identifier format is invalid" => "El formato del identificador del rol es incorrecto",
    "Group name and description are mandatory" => "El nombre y la descripción del rol es obligatorio",
    "Group name is mandatory" => "El nombre del rol es obligatorio",
    "Group name can't be larger than 50 characters" => "El nombre del rol no puede tener más de 50 caracteres",
    "Group name format is invalid" => "El formato del nombre del rol es incorrecto",
    "Group description is mandatory" => "La descripción de la funcionalidad es obligatorio",
    "Group description can't be larger than 255 characters" => "La descripción del rol no puede tener más de 255 caracteres",
    "Group description format is invalid" => "El formato de la descripción del rol es incorrecto",
    "Group doesn't exist" => "El rol no existe",

)

?>
