<?php
//CADENAS UTILIZADAS EN CASTELLANO
$strings = array(
"Edit" => "edit",
"Add"=> "add",
"Show" => "Ver",
"Delete" => "Eliminar",
"Building" => "Edificio: ",
"Buildings" => "Edificios",
"idBuilding" => "Identificador",
"nameBuilding" => "Edificio ",
"addressBuilding" => "Dirección",
"phoneBuilding" => "Teléfono",
"responsibleBuilding" => "Responsable",
"You do not have the necessary permits" => "No tienes los permisos necesarios",
"Attention" => "Atención",
"Are you sure you want to delete the building \"%s\" ?" => "¿Está seguro de querer eliminar el edificio \"%s\" ?",
"The information that this building has will be lost" => "La información que tiene este edificio se perderá",
"Cancel" => "Cancelar",
"Ok" => "Ok",
"Datas of the new building" => "Datos del nuevo edificio",
"Do you want to change something?" => "¿Quieres modificar alguna información del edificio?",
"Save" => "Guardar",
"Back" => "Volver",
"What is the identifier of this building?" => "¿Cuál es el identificador de este edificio?",
"What building is it?" => "¿Qué edificio es?",
"What is your postal address?" => "¿Cuál es su dirección?",
"What is your phone?" => "¿Cuál es su teléfono?",
"Who is the responsible?" => "¿Quién es el responsable?",
"Building \"%s\" successfully updated." => "El edificio \"%s\" se ha modificado con éxito",
"Floors" => "Plantas",
"Show Floor" => "Ver planta",
"Edit Building" => "Editar Edificio",
"Delete Building" => "Eliminar Edificio",
"Add Building" => "Añadir Edificio",
"Show Building" => "Ver Edificio",
"Building \"%s\" successfully added." => "El edificio \"%s\" se ha añadido con éxito",
"Building \"%s\" successfully deleted." => "El edificio \"%s\" se ha eliminado con éxito",

"Floor" => "Planta: ",
"Information about the building's floors" =>"Información sobre las plantas del edificio",
"idBuildingidFloor" => "Identificador",
"idFloor" => "Identificador",
"nameFloor" => "Piso",
"planeFloor" => "Plano",
"surfaceBuildingFloor" => "Sup. Construida",
"surfaceUsefulFloor" => "Sup. Útil",
"Show Spaces" => "Ver Espacios",
"Data of the new building's floor" => "Datos del nuevo piso del edificio",
"Are you sure you want to delete the floor \"%s\"?" => "¿Está seguro de querer eliminar la planta \"%s\"?",
"The information that this floor has will be lost" => "La información que tiene esta planta se perderá",
"What is the identifier of this floor?" => "¿Cuál es el identificador de la planta?",
"What floor is it?" => "¿Qué planta es?",
"Is there a plan for this floor?" => "¿Hay plano de esta planta?",
"What is the constructed surface?" => "¿Cuál es la superficie construída?",
"What is the useful surface?" => "¿Cuál es la superficie útil?",
"Floor \"%s\" successfully updated." => "La planta \"%s\" se ha modificado con éxito",
"Add Floor" => "Añadir Planta",
"Edit Floor" => "Editar Planta",
"Show Floors" => "Ver Plantas",
"Floor \"%s\" successfully added." => "La planta \"%s\" se ha añadido con éxito",
"Floor \"%s\" successfully deleted." => "La planta \"%s\" se ha eliminado con éxito",

"Spaces" => "Espacios",
"idSpace" => "Identificador",
"nameSpace" => "Espacio",
"surfaceSpace" => "Sup. Espacio",
"numberInventorySpace" => "Núm. Inventario",
"Information about the building's spaces" => "Información sobre los espacios del edificio",
"Show Space" => "Ver Espacio",
"Add Space" => "Añadir Espacio",
"Edit Space" => "Editar Espacio",
"Delete Space" => "Eliminar Espacio",
"Show Space" => "Ver Espacio",
"Data of the new space" => "Datos del nuevo espacio",
"What is the identifier of this space?" => "¿Cuál es el identificador del nuevo espacio?",
"What space is it?" => "¿Qué espacio es?",
"What is the number inventory?" => "¿Cuál es su número de inventario?",
"What is the surface of space?" => "¿Cuál es la superficie del espacio?",
"Space \"%s\" successfully added." => "El espacio \"%s\" se ha añadido con éxito",
"Space \"%s\" successfully updated." => "El espacio \"%s\" se ha actualizado con éxito",
"Building, floor and space id are mandatory" => "El id del edificio, la planta y el espacio son obligatorios",
"Building and floor id is mandatory" => "El id del edificio y la planta son obligatorios",
"No exist space to delete" => "No existe el espacio a eliminar",
"Space \"%s\" successfully deleted." => "El espacio \"%s\" se ha eliminado con éxito",
"Are you sure you want to delete the space \"%s\" ?" => "¿Está seguro de querer eliminar el espacio \"%s\" ?",
"The information that this space has will be lost" => "La información que tiene este espacio se perderá",



//BD
"Error in the query on the database" => "Error en la consulta sobre la base de datos",


//VALIDATES
//BUILDING
"Building id is mandatory" => "El identificador del edificio es obligatorio",
"Building id can not be that long" =>"El identificador del edificio es demasiado largo",
"Building id is invalid. Example: OSBI0" => "El identificador es inválido. Por ejemplo: OSBI0",
"There is already a building with that id" => "Ya existe un edificio con ese id",
"Building name is mandatory" => "El nombre del edificio es obligatorio",
"Building name can not be that long" => "El nombre del edificio es demasiado largo",
"Building name is invalid. Try again!" => "El formato del nombre del edificio es incorrecto. Pruebe otra vez!",
"Building address is mandatory" => "La dirección del edificio es obligatoria",
"Building address can not be that long" => "La dirección del edificio es demasiado larga",
"Building address is invalid. Try again!" => "El formato de la dirección del edificio es incorrecta",
"Building phone is incorrect. Example: 666777888" => "El teléfono del edificio es incorrecto. Ejemplo: 666777888",
"Building phone is invalid. Example: 666777888" => "El teléfono es inválido. Ejemplo: 666777888",
"Building responsible name can not be that long" => "El nombre del responsable del edificio es demasiado largo",
"Building responsible name is invalid. Try again!" => "El nombre del responsable del edificio es inválido. Pruebe otra vez",



//FLOOR
"Floor id is mandatory" => "El identificador de la planta es obligatorio",
"Floor id can not be that long" => "El identificador de la planta es demasiado largo. Por ejemplo: 00, S1 ",
"Floor id is invalid. Example: 00,S1" => "El identificador es inválido. Por ejemplo: 00,S1",
"There is already a floor with that id in this building" => "Ya existe una planta con ese id en este edificio",
"Floor name is mandatory" => "El nombre de la planta es obligatorio",
"Floor name can not be that long" => "El nombre de la planta no puede ser tan largo",
"Floor name is invalid. Try again!" => "El nombre es inválido. Pruebe otra vez!",
"Floor surface can not be that long" => "La superficie de la planta no puede ser tan grande",
"Floor useful surface can not be that long" => "La superficie útil de la planta no puede ser tan grande",
"The usable surface can not be greater than the building surface." => "La superficie útil de la planta no puede ser mayor que la superficie de la misma",

)
?>
