<?php
//CADENAS UTILIZADAS EN CASTELLANO
$strings = array(
"Edit" => "edit",
"Add"=> "add",
"Show" => "Ver",
"Delete" => "Eliminar",
"Building" => "Edificio: ",
"Buildings" => "Edificios",
"idBuilding" => "Identificador",
"nameBuilding" => "Edificio ",
"addressBuilding" => "Dirección",
"phoneBuilding" => "Teléfono",
"responsibleBuilding" => "Responsable",
"Attention" => "Atención",
"Are you sure you want to delete this building?" => "Está seguro de querer eliminar este edificio?",
"The information that this building has will be lost" => "La información que tiene este edificio se perderá",
"Cancel" => "Cancelar",
"Ok" => "Ok",
"Datas of the new building" => "Datos del nuevo edificio",
"Do you want to change something?" => "¿Quieres modificar alguna información del edificio?",
"Save" => "Guardar",
"Back" => "Volver",
"What is the identifier of this building?" => "¿Cuál es el identificador de este edificio?",
"What building is it?" => "¿Qué edificio es?",
"What is your postal address?" => "¿Cuál es su dirección?",
"What is your phone?" => "¿Cuál es su teléfono?",
"Who is the responsible?" => "¿Quién es el responsable?",
"Building \"%s\" successfully updated." => "El edificio \"%s\" se ha modificado con éxito",
"Floors" => "Plantas",
"Show Floor" => "Ver planta",
"Edit Building" => "Editar Edificio",
"Delete Building" => "Eliminar Edificio",
"Add Building" => "Añadir Edificio",
"Show Building" => "Ver Edificio",
"Building \"%s\" successfully added." => "El edificio \"%s\" se ha añadido con éxito",
"Building \"%s\" successfully deleted." => "El edificio \"%s\" se ha eliminado con éxito",

"Floor" => "Planta: ",
"Information about the building's floors" =>"Información sobre las plantas del edificio",
"idBuildingidFloor" => "Identificador",
"idFloor" => "Identificador",
"nameFloor" => "Piso",
"planeFloor" => "Plano",
"surfaceBuildingFloor" => "Sup. Construida",
"surfaceUsefulFloor" => "Sup. Útil",
"Show Spaces" => "Ver Espacios",
"Data of the new building's floor" => "Datos del nuevo piso del edificio",
"Are you sure you want to delete this floor?" => "Está seguro de querer eliminar esta planta?",
"The information that this floor has will be lost" => "La información que tiene esta planta se perderá",
"What is the identifier of this floor?" => "¿Cuál es el identificador de la planta?",
"What floor is it?" => "¿Qué planta es?",
"Is there a plan for this floor?" => "¿Hay plano de esta planta?",
"What is the constructed surface?" => "¿Cuál es la superficie construída?",
"What is the useful surface?" => "¿Cuál es la superficie útil?",
"Floor \"%s\" successfully updated." => "La planta \"%s\" se ha modificado con éxito",
"Add Floor" => "Añadir Planta",
"Edit Floor" => "Editar Planta",
"Show Floor" => "Ver Planta",
"Floor \"%s\" successfully added." => "La planta \"%s\" se ha añadido con éxito",
"Floor \"%s\" successfully deleted." => "La planta \"%s\" se ha eliminado con éxito",

"Spaces" => "Espacios",
"idSpace" => "Identificador",
"nameSpace" => "Espacio",
"surfaceSpace" => "Sup. Espacio",
"numberInventorySpace" => "Núm. Inventario",
"Information about the building's spaces" => "Información sobre los espacios del edificio",
"Show Space" => "Ver Espacio",
"Add Space" => "Añadir Espacio",
"Edit Space" => "Editar Espacio",
"Delete Space" => "Eliminar Espacio",
"Show Space" => "Ver Espacio",

)
?>
