<?php
//CADENAS UTILIZADAS EN CASTELLANO
$strings = array(
    "Add"=> "Añadir",
    "Edit" => "Edit",
    "Show" => "Ver",
    "Delete" => "Eliminar",
    "Search" => "Buscar",
    "Building" => "Edificio: ",
    "Buildings" => "Edificios",
    "My Account" => "Mi Cuenta",
    "My Profile" => "Mi Perfil",
    "Logout" => "Salir",
    "Login" => "Login",
    "Functionalitys" => "Funcionalidades",
    "Permissions" => "Roles",
    "Spanish" => "Castellano",
    "Galician" => "Gallego",
    "English" => "Inglés",
    "Users" => "Usuarios",
    "Do you want to change something?" => "¿Quieres modificar alguna información?",
    "Save" => "  Guardar",
    "Back" => "Volver",

    "idBuilding" => "Identificador",
    "nameBuilding" => "Edificio ",
    "addressBuilding" => "Dirección",
    "phoneBuilding" => "Teléfono",
    "Floors" => "Plantas",
    "Show Floor" => "Ver planta",
    "Edit Building" => "Editar Edificio",
    "Delete Building" => "Eliminar Edificio",
    "Add Building" => "Añadir Edificio",
    "Show Building" => "Ver Edificio",
    "Attention" => "Atención",
    "Are you sure you want to delete the building \"%s\" ?" => "¿Está seguro de querer eliminar el edificio \"%s\" ?",
    "The information that this building has will be lost" => "La información que tiene este edificio se perderá",
    "Cancel" => "Cancelar",
    "Ok" => "Ok",
    "Datas of the new building" => "Datos del nuevo edificio",
    "What is the identifier of this building?" => "¿Cuál es el identificador de este edificio?*",
    "What building is it?" => "¿Qué edificio es?*",
    "What is your postal address?" => "¿Cuál es su dirección?",
    "What is your phone?" => "¿Cuál es su teléfono?",
    "Not in session. Add buildings requires login." => "Para añadir edificios debes estar loggueado",
    "Not in session. Edit buildings requires login." => "Para editar edificios debes estar loggueado",
    "Not in session. Delete buildings requires login." => "Para eliminar edificios debes estar loggueado",
    "You do not have the necessary permits" => "No tienes los permisos necesarios",
    "No such building with this id" => "No existe ningún edificio con ese identificador",
    "Building \"%s\" successfully added." => "El edificio \"%s\" se ha añadido con éxito",
    "Building \"%s\" successfully deleted." => "El edificio \"%s\" se ha eliminado con éxito",
    "Building \"%s\" successfully updated." => "El edificio \"%s\" se ha modificado con éxito",

   
    "Floor" => "Planta: ",
    "Information about the building's floors" =>"Información sobre las plantas del edificio",
    "idBuildingidFloor" => "Identificador",
    "idFloor" => "Identificador",
    "nameFloor" => "Piso",
    "planeFloor" => "Plano",
    "Plane" => "Plane",
    "surfaceBuildingFloor" => "Sup. Construida",
    "surfaceUsefulFloor" => "Sup. Útil",
    "Show Spaces" => "Ver Espacios",
    "Add Floor" => "Añadir Planta",
    "Edit Floor" => "Editar Planta",
    "Delete Floor"=>"Eliminar Planta",
    "Show Floors" => "Ver Plantas",
    "Are you sure you want to delete the floor \"%s\"?" => "¿Está seguro de querer eliminar la planta \"%s\"?",
    "The information that this floor has will be lost" => "La información que tiene esta planta se perderá",
    "Data of the new building's floor" => "Datos del nuevo piso del edificio",
    "What is the identifier of this floor?" => "¿Cuál es el identificador de la planta?",
    "What floor is it?" => "¿Qué planta es?",
    "Is there a plan for this floor?" => "¿Hay plano de esta planta?",
    "What is the constructed surface?" => "¿Cuál es la superficie construída?",
    "What is the useful surface?" => "¿Cuál es la superficie útil?",
    "Not in session. Add floors requires login." => "Para añadir edificios debes estar loggueado",
    "Not in session. Edit floors requires login." => "Para editar edificios debes estar loggueado",
    "Not in session. Delete floors requires login." => "Para eliminar edificios debes estar loggueado",
    "Floor \"%s\" successfully updated." => "La planta \"%s\" se ha modificado con éxito",
    "Floor \"%s\" successfully added." => "La planta \"%s\" se ha añadido con éxito",
    "Floor \"%s\" successfully deleted." => "La planta \"%s\" se ha eliminado con éxito",
    "Show Plane" => "Ver Plano",
    "ShowPlane" => "ShowPlane",




    "Information about the building's spaces" => "Información sobre los espacios del edificio",
    "Spaces" => "Espacios",
    "idSpace" => "Identificador",
    "nameSpace" => "Espacio",
    "surfaceSpace" => "Sup. Espacio",
    "numberInventorySpace" => "Núm. Inventario",
    "Show Space" => "Ver Espacio",
    "Add Space" => "Añadir Espacio",
    "Edit Space" => "Editar Espacio",
    "Delete Space" => "Eliminar Espacio",
    "Show Space" => "Ver Espacio",
    "SelectSpacePlane" => "SelectSpacePlane",
    "ShowSpacePlane" => "ShowSpacePlane",
    "EditSpacePlane" => "EditSpacePlane",
    "Are you sure you want to delete the space \"%s\" ?" => "¿Está seguro de querer eliminar el espacio \"%s\" ?",
    "The information that this space has will be lost" => "La información que tiene este espacio se perderá",
    
    "Clear" => "Eliminar",
    "Plane successfully updated" => "Plano correctamente actualizado",
    "Select the space in the plane" => "Selecciona el espacio en el plano haciendo click en sus vértices",
    "ViewSpace" => "Ver Espacio",
    "SelectSpace" => "Seleccionar Espacio",
    "EditSpace" => "Editar Espacio",
    "Data of the new space" => "Datos del nuevo espacio",
    "What is the identifier of this space?" => "¿Cuál es el identificador del nuevo espacio? *",
    "What space is it?" => "¿Qué espacio es? *",
    "What is the number inventory?" => "¿Cuál es su número de inventario?",
    "What is the surface of space?" => "¿Cuál es la superficie del espacio?",
    "Space \"%s\" successfully added." => "El espacio \"%s\" se ha añadido con éxito",
    "Space \"%s\" successfully updated." => "El espacio \"%s\" se ha actualizado con éxito",
    "Space \"%s\" successfully deleted." => "El espacio \"%s\" se ha eliminado con éxito",
    "Building, floor and space id are mandatory" => "El id del edificio, la planta y el espacio son obligatorios",
    "Building and floor id is mandatory" => "El id del edificio y la planta son obligatorios",
    "No exist space to delete" => "No existe el espacio a eliminar",
    "Not in session. Add space requires login." => "Para añadir un espacio debes estar logueado",
    "Not in session. Edit space requires login." => "Para modificar un espacio debes estar logueado",
    "Not in session. Delete space requires login." => "Para eliminar un espacio debes estar logueado",

    "photo" => "Foto",
    "username" => "Usuario",
    "passwd" => "Contraseña",
    "name" => "Nombre",
    "surname"=> "Apellidos",
    "dni" => "DNI",
    "bithdate" => "Fecha",
    "email" => "Email",
    "phone" => "Teléfono",
    "photo" => "Foto",
    "ProfilePhoto" => "Foto de perfil",
    "Show Users" => "Ver Usuarios",
    "User \"%s\" successfully added." => "El usuario \"%s\" se ha añadido con éxito",
    "User \"%s\" successfully updated." => "El usuario \"%s\" se ha actualizado con éxito",
    "No exist user to delete" => "No existe el usuario a eliminar",
    "User \"%s\" successfully deleted." => "El usuario \"%s\" se ha eliminado con éxito",
    "Not in session. Add users requires login." => "Para añadir usuarios debes estar logueado",
    "Not in session. Edit user requires login." => "Para editar un usuario debes estar logueado",
    "Not in session. Add users requires login." => "Para eliminar usuarios debes estar logueado",
    "No such user with this id" => "No existe ningún usuario con ese username",
    "Are you sure you want to delete the user \"%s\" ?" => "¿Está seguro de querer eliminar el usuario \"%s\" ?",
    "The information that this user has will be lost" => "La información que tiene este usuario se perderá",
    "Add User" => "Añadir usuario",
    "Show User" => "Ver usuario",
    "Edit User" => "Editar usuario",
    "Delete User" => "Eliminar usuario",
    "New user" => "Nuevo usuario",
    "What is the username of this user?" => "¿Cuál es el username? *",
    "What is the password of this user?" => "¿Cuál es la contraseña del usuario? *",
    "Repeat password" => "Vuelva a escribir la contraseña *",
    "Repeat new password" => "Vuelva a escribir la contraseña",
    "What is the name of the user?" => "¿Cuál es el nombre del usuario? *",
    "What are the user's surnames?" => "¿Cuáles son los apellidos del usuario? *",
    'What is your ID?' => "¿Cuál es el DNI del usuario? *",
    "What is his birthdate?" => "¿Cuál es la fecha de nacimiento del usuario? *",
    "What is his email?" => "¿Cuál es el email del usuario? *",
    "What is his phone?" => "¿Cuál es el teléfono del usuario?",
    "Do you want to change the password?" => "¿Quieres cambiar la contraseña? ",
    "PasswordCharacters"=> "Mínimo 8 caracteres",
    "PasswordLowercase"=> "Una minúscula",
    "PasswordUppercase"=> "Una mayúscula",
    "PasswordNumber"=> "Un número",

    "Functionalities" => "Funcionalidades",
    "nameFunction" => "Nombre",
    "descripFunction" => "Descripción",
    "Add Functionality" => "Nueva Funcionalidad",
    "Show Functionality" => "Ver Funcionalidad",
    "Edit Functionality" => "Editar Funcionalidad",
    "Delete Functionality" => "Eliminar Funcionalidad",
    "Datas of the new functionality" => "Datos de la nueva funcionalidad",
    "What functionality is it?" => "¿Qué funcionalidad es?",
    "What is the functionality about?" => "¿De qué trata la funcionalidad?",
    "Check the actions:" => "Seleccione las acciones:",
    "Are you sure you want to delete the functionality \"%s\" ?" => "¿Está seguro de querer eliminar la funcionalidad \"%s\" ?",
    "The information that this functionality has will be lost" => "La información de esta funcionalidad se perderá",
    "Function id is mandatory" => "El id de la funcionalidad es obligartorio",
    "Not in session. Add functionalities requires login." => "Para añadir funcionalidades debes estar loggueado",
    "Not in session. Edit functionalities requires login." => "Para editar funcionalidades debes estar logueado",
    "Not in session. Delete functionalities requires login." => "Para eliminar funcionalidades debes estar logueado",
    "Functionality \"%s\" successfully added." => "La funcionalidad \"%s\" se ha añadido con éxito",
    "Function \"%s\" successfully updated." => "La funcionalidad \"%s\" se ha modificado con éxito",
    "Function \"%s\" successfully deleted." => "La funcionalidad \"%s\" se ha eliminado con éxito",


    "Not in session. Add group requires login." => "Para añadir roles debes estar logueado",
    "Not in session. Delete groups requires login." => "Para eliminar roles debes estar logueado",
    "Not in session. Edit groups requires login." => "Para modificar roles debes estar logueado",
    "Group id is mandatory" => "El identificador del rol es obligatorio",
    "No such group with this id" => "No existe ningún rol con ese identificador",
    "Groups" => "Roles",
    "nameGroup" => "Rol",
    "descripGroup" => "Descripción",
    "Add Group" => "Añadir Rol",
    "Delete Group" => "Eliminar Rol",
    "Edit Group" => "Editar Rol",
    "Show Group" => "Ver Rol",
    "Are you sure you want to delete the group \"%s\" ?" => "¿Está seguro de querer eliminar el rol \"%s\" ?",
    "The information that this group has will be lost" => "La información de este rol se perderá",
    "Group \"%s\" successfully added." => "El rol \"%s\" se ha añadido con éxito",
    "Group \"%s\" successfully updated." => "El rol \"%s\" se ha modificado con éxito",
    "Group \"%s\" successfully deleted." => "El rol \"%s\" se ha eliminado con éxito",
    "Datas of the new group" => "Datos del nuevo rol",
    "What group is it?" => "¿Nombre del Rol?",
    "What is the group about?" => "Describe el rol brevemente",

    "Not in session. Add actions requires login." => "Para añadir acciones debes estar logueado",
    "Not in session. Delete actions requires login." => "Para eliminar acciones debes estar logueado",
    "Not in session. Edit actions requires login." => "Para modificar acciones debes estar logueado",
    "Actions" => "Acciones",
    "nameAction" => "Acción",
    "descripAction" => "Descripción",
    "Add Action" => "Añadir Acción",
    "Delete Action" => "Eliminar Acción",
    "Edit Action" => "Editar Acción",
    "Show Action" => "Ver Acción",
    "Are you sure you want to delete the action \"%s\" ?" => "¿Está seguro de querer eliminar la acción \"%s\" ?",
    "The information that this action has will be lost" => "La información de esta acción se perderá",
    "Action id is mandatory" => "El identificador de la acción es obligatorio",
    "No such action with this id" => "No existe ninguna acción con ese identificador",

    "Action \"%s\" successfully added." => "La acción \"%s\" se ha añadido con éxito",
    "Action \"%s\" successfully updated." => "La acción \"%s\" se ha modificado con éxito",
    "Action \"%s\" successfully deleted." => "La acción \"%s\" se ha eliminado con éxito",
    "Datas of the new action" => "Datos de la nueva acción",
    "What action is it?" => "¿Nombre de la acción?",
    "What is the action about?" => "Describe la acción brevemente",



    //BD
    "Error in the query on the database" => "Error en la consulta sobre la base de datos",


    //VALIDATES
    //BUILDING
    "Building id is mandatory" => "El identificador del edificio es obligatorio",
    "Building id can not be that long" =>"El identificador del edificio es demasiado largo",
    "Building id is invalid. Example: OSBI0" => "El identificador es inválido. Por ejemplo: OSBI0",
    "There is already a building with that id" => "Ya existe un edificio con ese id",
    "Building name is mandatory" => "El nombre del edificio es obligatorio",
    "Building name can not be that long" => "El nombre del edificio es demasiado largo",
    "Building name is invalid. Try again!" => "El formato del nombre del edificio es incorrecto. Pruebe otra vez!",
    "Building address is mandatory" => "La dirección del edificio es obligatoria",
    "Building address can not be that long" => "La dirección del edificio es demasiado larga",
    "Building address is invalid. Try again!" => "El formato de la dirección del edificio es incorrecta",
    "Building phone is incorrect. Example: 666777888" => "El teléfono del edificio es incorrecto. Ejemplo: 666777888",
    "Building phone is invalid. Example: 666777888" => "El teléfono es inválido. Ejemplo: 666777888",
    "Building responsible name can not be that long" => "El nombre del responsable del edificio es demasiado largo",
    "Building responsible name is invalid. Try again!" => "El nombre del responsable del edificio es inválido. Pruebe otra vez",



    //FLOOR
    "Floor id is mandatory" => "El identificador de la planta es obligatorio",
    "Floor id can not be that long" => "El identificador de la planta es demasiado largo. Por ejemplo: 00, S1 ",
    "Floor id is invalid. Example: 00,S1" => "El identificador es inválido. Por ejemplo: 00,S1",
    "There is already a floor with that id in this building" => "Ya existe una planta con ese id en este edificio",
    "Floor name is mandatory" => "El nombre de la planta es obligatorio",
    "Floor name can not be that long" => "El nombre de la planta no puede ser tan largo",
    "Floor name is invalid. Try again!" => "El nombre es inválido. Pruebe otra vez!",
    "Floor surface can not be that long" => "La superficie de la planta no puede ser tan grande",
    "Floor useful surface can not be that long" => "La superficie útil de la planta no puede ser tan grande",
    "The usable surface can not be greater than the building surface." => "La superficie útil de la planta no puede ser mayor que la superficie de la misma",


    //SPACE
    "Space id is mandatory" => "El id del espacio es obligatorio",
    "Space id can not be that long" => "El id del espacio es demasiado largo. Ejemplo: 000007",
    "Space id is invalid. Example: 000011" => "El id es inválido. Ejemplo: 000011",
    "There is already a space with that id in this floor" => "Ya existe un espacio en esta planta con ese id",
    "Space name is mandatory" => "El nombre del espacio es obligatorio",
    "Space name can not be that long" => "El nombre del espacio es demasiado largo",
    "Space name is invalid. Try again!" => "El nombre del espacio es inválido. Prueba otra vez!",
    "Space surface can not be that long" => "La superficie del espacio es demasiado grande",


    //USER
    "Username or password is incorrect" => "El username o la contraseña es incorrecto",
    "Username is mandatory" => "El nick de usuario es obligatorio",
    "Username can not be that long" => "El nick de usuario no puede ser tan largo",
    "Username is invalid" => "El nick de usuario es inválido",
    "There is already a user with that username" => "Ya existe un usuario con ese nick",
    "Password is mandatory" => "La contraseña es obligatoria",
    "Password can not be that long" => "La contraseña no puede ser tan larga",
    "Password is invalid. Try again!" => "La contraseña es inválida. ¡Prueba otra vez!",
    "User name is mandatory" => "El nombre del usuario es obligatorio",
    "User name can not be that long" => "El nombre del usuario no puede ser tan largo",
    "User name is invalid. Try again!" => "El nombre de usuario es inválido. ¡Prueba otra vez!",
    "User surnames are mandatory" => "Los apellidos son obligatorios",
    "User surnames can not be that long" => "Los apellidos no pueden ser tan largos",
    "User surnames are invalid. Try again!" => "Los apellidos son inválidos. ¡Prueba otra vez!",
    "DNI can not be that long" => "El DNI es incorrecto",
    "There is already a user with that dni" => "Ya existe un usuario con ese DNI",
    "User id is invalid. Try again!" => "El DNI es inválido. ¡Prueba otra vez!",
    "User id letter is invalid. Try again!" => "La letra del DNI es inválida. ¡Prueba otra vez!",
    "Birthdate is incorrect" => "La fecha de nacimiento es incorrecta",
    "Email can not be that long" => "El email es demasiado largo",
    "Email is invalid" => "Email inválido",
    "There is aready a user with that email" => "Ya existe un usuario con ese email",
    "User phone is incorrect. Example: 666777888" => "El teléfono es inválido. Ejemplo: 666777888",
    "User phone format is invalid. Example: 666777888" => "El formato del teléfono es inválido. Ejemplo: 666777888"




)

?>
